// Generated by https://quicktype.io

import { Process } from "./Process";

export class Consult {
    id!:             number;
    diagnostic!:     string;
    consultComment!: string;
    consultDate!:    Date;
    timestamp!:      string;
    medicalProcess!: Process;
}

 

 