// Generated by https://quicktype.io

import { Patient } from "./Patient";

export class Process {
    id!:        number;
    medic!:     Medic;
    patient!:   Patient;
    timestamp!: string;
}

export class Medic {
    id!:        number;
    name!:      string;
    birthDate!: string;
    address!:   string;
    cellPhone!: string;
}

 
